If Python is your phone, pandas is the Instagram app—your go-to tool for posting, filtering, and analyzing data! Think about it: just like Instagram helps you crop, filter, and caption your photos, pandas helps you clean, filter, and organize your data.

# Why Pandas
Excel is great, but when your data gets messy, big, or just plain annoying, Excel starts crying for help.

## 🐼 Core Capabilities of Pandas

Pandas is built on top of the NumPy library and offers high-performance, easy-to-use data structures and data analysis tools.

### 1\. Data Loading and Saving

Pandas allows you to easily read and write data from various formats, making it highly versatile.

*   **Loading:** It can read data from **CSV** files (the most common format), Excel sheets, SQL databases, JSON, and even plain text files. The primary function for this is `pd.read_csv()`.
    
    *   _Example:_ `df = pd.read_csv('data.csv')`
        
*   **Saving:** You can export your cleaned or processed DataFrame back into these formats using methods like `df.to_csv()`.
    

### 2\. Data Inspection and Exploration

Once data is loaded, you need tools to understand its structure and content.

*   **Viewing Data:**
    
    *   `df.head()` and `df.tail()`: Show the first and last $N$ rows, respectively, to get a quick glimpse of the data.
        
    *   `df.sample()`: Returns a random sample of rows.
        
*   **Summary Statistics:**
    
    *   `df.info()`: Provides a concise summary of the DataFrame, including the number of entries, the data type of each column (Dtype), and the count of non-null values.
        
    *   `df.describe()`: Generates descriptive statistics (count, mean, standard deviation, min, max, quartiles) of the numerical columns.
        
*   **Unique Values:**
    
    *   `df['column_name'].value_counts()`: Lists all unique values in a column and how many times each value appears, crucial for understanding categorical features.
        

### 3\. Data Cleaning and Preprocessing

This is often the most time-consuming part of machine learning, and Pandas simplifies many common tasks.

*   **Handling Missing Data (NaNs):**
    
    *   `df.isnull()`: Generates a boolean mask indicating where data is missing.
        
    *   `df.dropna()`: Removes rows or columns that contain missing values.
        
    *   `df.fillna()`: Fills missing values with a specified value (e.g., the mean, median, or a constant).
        
*   **Data Type Conversion:**
    
    *   `df['column'] = df['column'].astype(new_type)`: Used to change a column's data type, for example, converting a string column to a numeric one or an integer to a category.
        
*   **Removing Duplicates:**
    
    *   `df.drop_duplicates()`: Identifies and removes duplicate rows.
        

### 4\. Data Selection, Indexing, and Subsetting

Pandas provides intuitive ways to access specific parts of the data.

*   **Selecting Columns:** Accessing a column is similar to accessing a dictionary key: `df['column_name']`.
    
*   **Filtering Rows:** Use boolean masks for powerful conditional selection: `df[df['age'] > 30]`.
    
*   **Location-based Indexing:**
    
    *   `df.loc[]`: Primarily used for **label-based** indexing (using row/column names).
        
    *   `df.iloc[]`: Primarily used for **integer position-based** indexing (using numerical indices).
        

### 5\. Grouping and Aggregation

This allows for applying functions to subsets of the data, similar to the "Group By" clause in SQL.

*   **The `groupby()` method:** Splits the DataFrame into groups based on some criterion.
    
    *   Example: To find the average salary per department:
        
        df.groupby('Department')\['Salary'\].mean()
        
    *   Common aggregation functions include `mean()`, `sum()`, `count()`, `min()`, and `max()`.

In [ ]:
import pandas as pd
from IPython.display import display

# -------- Load DataFrame --------
df = pd.read_csv("employees.csv")
display(df)

,First Name,Gender,JoiningYear,Education,Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.0,Bachelors,97308.0,6.945,True,Marketing,34.0,No,Bangalore
1,Thomas,Male,2013.0,Bachelors,61933.0,4.170,True,NaN,28.0,No,Pune
2,Maria,Female,2014.0,Bachelors,130590.0,11.858,False,Finance,38.0,No,New Delhi
3,Jerry,Male,2016.0,Masters,138705.0,9.340,True,Finance,27.0,No,Bangalore
4,Larry,Male,2017.0,Masters,101004.0,1.389,True,Client Services,24.0,Yes,Pune
...,...,...,...,...,...,...,...,...,...,...,...
998,Larry,Male,2015.0,Bachelors,60500.0,11.985,False,Business Development,28.0,No,Bangalore
999,Albert,Male,2012.0,Bachelors,129949.0,10.169,True,Sales,26.0,No,Pune
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,New Delhi
1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pune
1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Delhi

In [ ]:
# -------- Data Overview --------
df.info()
display(df.head())
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   JoiningYear        1000 non-null   float64
 3   Education          1000 non-null   object
 4   Salary             1000 non-null   float64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Department         957 non-null    object
 8   Age                1000 non-null   float64
 9   EverBenched        1001 non-null   object
 10  City               1003 non-null   object
dtypes: float64(4), object(7)
memory usage: 86.3+ KB

,First Name,Gender,JoiningYear,Education,Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.0,Bachelors,97308.0,6.945,True,Marketing,34.0,No,Bangalore
1,Thomas,Male,2013.0,Bachelors,61933.0,4.170,True,NaN,28.0,No,Pune
2,Maria,Female,2014.0,Bachelors,130590.0,11.858,False,Finance,38.0,No,New Delhi
3,Jerry,Male,2016.0,Masters,138705.0,9.340,True,Finance,27.0,No,Bangalore
4,Larry,Male,2017.0,Masters,101004.0,1.389,True,Client Services,24.0,Yes,Pune

       JoiningYear         Salary      Bonus %          Age
count  1000.000000    1000.000000  1000.000000  1000.000000
mean   2015.114000   90662.181000    10.207555    26.491000
std       1.851603   32923.693342     5.528481     2.574597
min    2012.000000   35013.000000     1.015000    22.000000
25%    2014.000000   62613.000000     5.401750    25.000000
50%    2015.000000   90428.000000     9.838500    26.000000
75%    2017.000000  118740.250000    14.838000    27.000000
max    2018.000000  149908.000000    19.944000    40.000000

from matplotlib import pyplot as plt
_df_0['JoiningYear'].plot(kind='hist', bins=20, title='JoiningYear')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Salary'].plot(kind='hist', bins=20, title='Salary')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Bonus %'].plot(kind='hist', bins=20, title='Bonus %')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='JoiningYear', y='Salary', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Salary', y='Bonus %', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Bonus %', y='Age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7['JoiningYear'].plot(kind='line', figsize=(8, 4), title='JoiningYear')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['Salary'].plot(kind='line', figsize=(8, 4), title='Salary')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Bonus %'].plot(kind='line', figsize=(8, 4), title='Bonus %')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
# -------- Missing Data Handling --------
print(df.isnull().sum())

df_dropna = df.dropna()
df_fillna_zero = df.fillna(0)
df_fillna_mean = df.fillna(df.mean(numeric_only=True))

display(df_dropna)
display(df_fillna_zero)
display(df_fillna_mean)

First Name            70
Gender               148
JoiningYear            3
Education              3
Salary                 3
Bonus %                3
Senior Management     70
Department            46
Age                    3
EverBenched            2
City                   0
dtype: int64

,First Name,Gender,JoiningYear,Education,Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.0,Bachelors,97308.0,6.945,True,Marketing,34.0,No,Bangalore
2,Maria,Female,2014.0,Bachelors,130590.0,11.858,False,Finance,38.0,No,New Delhi
3,Jerry,Male,2016.0,Masters,138705.0,9.340,True,Finance,27.0,No,Bangalore
4,Larry,Male,2017.0,Masters,101004.0,1.389,True,Client Services,24.0,Yes,Pune
5,Dennis,Male,2016.0,Bachelors,115163.0,10.125,False,Legal,22.0,No,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...
994,George,Male,2014.0,Bachelors,98874.0,4.479,True,Marketing,24.0,No,Bangalore
996,Phillip,Male,2014.0,Bachelors,42392.0,19.675,False,Finance,26.0,No,Pune
997,Russell,Male,2016.0,Bachelors,96914.0,1.421,False,Product,28.0,No,New Delhi
998,Larry,Male,2015.0,Bachelors,60500.0,11.985,False,Business Development,28.0,No,Bangalore
999,Albert,Male,2012.0,Bachelors,129949.0,10.169,True,Sales,26.0,No,Pune

,First Name,Gender,JoiningYear,Education,Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.0,Bachelors,97308.0,6.945,True,Marketing,34.0,No,Bangalore
1,Thomas,Male,2013.0,Bachelors,61933.0,4.170,True,0,28.0,No,Pune
2,Maria,Female,2014.0,Bachelors,130590.0,11.858,False,Finance,38.0,No,New Delhi
3,Jerry,Male,2016.0,Masters,138705.0,9.340,True,Finance,27.0,No,Bangalore
4,Larry,Male,2017.0,Masters,101004.0,1.389,True,Client Services,24.0,Yes,Pune
...,...,...,...,...,...,...,...,...,...,...,...
998,Larry,Male,2015.0,Bachelors,60500.0,11.985,False,Business Development,28.0,No,Bangalore
999,Albert,Male,2012.0,Bachelors,129949.0,10.169,True,Sales,26.0,No,Pune
1000,0,0,0.0,0,0.0,0.000,0,0,0.0,No,New Delhi
1001,0,0,0.0,0,0.0,0.000,0,0,0.0,0,Pune
1002,0,0,0.0,0,0.0,0.000,0,0,0.0,0,New Delhi

,First Name,Gender,JoiningYear,Education,Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.000,Bachelors,97308.000,6.945000,True,Marketing,34.000,No,Bangalore
1,Thomas,Male,2013.000,Bachelors,61933.000,4.170000,True,NaN,28.000,No,Pune
2,Maria,Female,2014.000,Bachelors,130590.000,11.858000,False,Finance,38.000,No,New Delhi
3,Jerry,Male,2016.000,Masters,138705.000,9.340000,True,Finance,27.000,No,Bangalore
4,Larry,Male,2017.000,Masters,101004.000,1.389000,True,Client Services,24.000,Yes,Pune
...,...,...,...,...,...,...,...,...,...,...,...
998,Larry,Male,2015.000,Bachelors,60500.000,11.985000,False,Business Development,28.000,No,Bangalore
999,Albert,Male,2012.000,Bachelors,129949.000,10.169000,True,Sales,26.000,No,Pune
1000,NaN,NaN,2015.114,NaN,90662.181,10.207555,NaN,NaN,26.491,No,New Delhi
1001,NaN,NaN,2015.114,NaN,90662.181,10.207555,NaN,NaN,26.491,NaN,Pune
1002,NaN,NaN,2015.114,NaN,90662.181,10.207555,NaN,NaN,26.491,NaN,New Delhi

In [ ]:
# -------- Data Cleaning Techniques --------

# Remove missing rows
df.dropna(inplace=True)

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Fill missing numeric values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# Fill missing string values with a placeholder
df.fillna("Unknown", inplace=True)

# Convert data types
df["Age"] = df["Age"].astype(int)

# Strip extra spaces from strings
df["First Name"] = df["First Name"].str.strip()

# Convert text to uniform case
df["Department"] = df["Department"].str.upper()

# Replace incorrect or inconsistent values
df.replace("IT DEPT", "IT", inplace=True)

# Remove unwanted characters (example)
df["First Name"] = df["First Name"].str.replace("[^a-zA-Z ]", "", regex=True)

# Reset index after cleaning
df.reset_index(drop=True, inplace=True)

display(df)

,First Name,Gender,JoiningYear,Education,Monthly_Salary,Bonus %,Senior Management,Department,Age,EverBenched,City
0,Douglas,Male,2017.0,Bachelors,97308.0,6.945,True,MARKETING,34,No,Bangalore
1,Maria,Female,2014.0,Bachelors,130590.0,11.858,False,FINANCE,38,No,New Delhi
2,Jerry,Male,2016.0,Masters,138705.0,9.340,True,FINANCE,27,No,Bangalore
3,Larry,Male,2017.0,Masters,101004.0,1.389,True,CLIENT SERVICES,24,Yes,Pune
4,Dennis,Male,2016.0,Bachelors,115163.0,10.125,False,LEGAL,22,No,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...
759,George,Male,2014.0,Bachelors,98874.0,4.479,True,MARKETING,24,No,Bangalore
760,Phillip,Male,2014.0,Bachelors,42392.0,19.675,False,FINANCE,26,No,Pune
761,Russell,Male,2016.0,Bachelors,96914.0,1.421,False,PRODUCT,28,No,New Delhi
762,Larry,Male,2015.0,Bachelors,60500.0,11.985,False,BUSINESS DEVELOPMENT,28,No,Bangalore
763,Albert,Male,2012.0,Bachelors,129949.0,10.169,True,SALES,26,No,Pune

In [ ]:
df.to_csv("cleaned_employees.csv", index=False)

In [ ]:

# -------- Basic Statistics --------
print(df["Monthly_Salary"].mean())
print(df["Monthly_Salary"].max())
print(df["Monthly_Salary"].min())
print(df["Monthly_Salary"].std())

90433.19633507854
149908.0
35013.0
32864.665282356